### ISSUE TITLE
Add Youfoodz

### ISSUE THREAD

**Issue by mlduff** [hhursev/recipe-scrapers#1120]
Please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login), and add sample recipe URL(s) below:

- https://www.youfoodz.com/recipes/fried-chicken-and-gravy-with-creamy-mash-and-peas-330g-660a5ea770e8f6aef4341156?week=2024-W19
- https://www.youfoodz.com/recipes/nonnas-spaghetti-bolognese-with-italian-herbs-and-garlic-300g-660a602770e8f6aef4341177?week=2024-W19

Will implement myself.

**Comment by jayaddison** [comment]
I've closed the pull request for this because I don't personally consider what YouFoodz are presenting here to be recipes.  That may be odd or overcautious, but I feel like what they're really presenting are ready-made food products, and so the instructions are not "how to combine ingredients to prepare a drink/meal" (what I'd consider to be a recipe) but "our company's guidelines to consumers about how this product of ours should be served".

It's not a hard-and-fast rule, but I think that a true recipe has to have the potential to stay valid if-and-when it outlasts the author(s), whether they're a person or a company, non-profit, government, AI or whatever other entities.

I don't think that's the case for the output of the scraper here - I know (or I think I know) approximately what's involved to prepare the spaghetti bolognese test case, but if I didn't, then the instructions as-is wouldn't be enough to approximate the meal from the constituent ingredient list.
