### ISSUE TITLE
Idea: port recipe-scrapers to rust?

### ISSUE THREAD

**Issue by jayaddison** [hhursev/recipe-scrapers#1324]
Maybe a strange idea; but I think that if our code is running frequently, there could be benefits to rewriting it in a language that is more performant and [energy efficient](https://sites.google.com/view/energy-efficiency-languages/results) than Python.

Ideally we would retain the Python API so that Python users could continue to install the package from PyPi and use it as-is.

Rust/Cargo users would be able to install the native version - although to begin with it might be less featureful.

**Comment by jknndy** [comment]
This seems like it could be beneficial to the library as a whole for performance and would be an interesting opportunity to explore the Rust ecosystem. Rust's focus on concurrency could offer a significant performance improvement for _power users_ and developers which could encourage new integrations!

That said, some concerns off the bat:
- Is there a draw to this library because it relies heavily on Python? 
- Would we be ostracizing existing developers who may not be familiar with Rust? On the flip side integrating Rust could draw new developers.

### Python API
It seems possible to maintain a functional Python API, even if the core logic shifts to Rust. From my research, the two most recommended tools for this are [PyO3](https://pyo3.rs/v0.15.1/) and [Maturin](https://www.maturin.rs/). 

### Existing required (& optional) dependencies
`beautifulsoup4` - [scraper ](https://docs.rs/scraper/latest/scraper/)and [html5ever](https://docs.rs/html5ever/latest/html5ever/) | `scraper` feels like the better fit here.
`extruct` - [`extruct`](https://docs.rs/extruct/latest/extruct/)
`isodate` - [`chrono`](https://docs.rs/chrono/latest/chrono/)
`requests` - [`reqwest`](https://docs.rs/reqwest/latest/reqwest/)

Overall, I think this is an interesting idea and could be worth the effort for the performance improvement alone.

**Comment by jayaddison** [comment]
Thanks @jknndy - that makes it all sound fairly feasible, at least in theory.  Perhaps we could try writing a proof-of-concept for a single, `schema.org`-only scraper in Rust, to get a sense for how much potential performance/overhead difference there could be.  I guess some of the overhead we have at the moment will relate to the size of this library -- load time for scraper modules, etc -- and so it wouldn't be an entirely equal/fair comparison, but it could give some kind of indication of whether a port might be worthwhile.

The community/contributor questions are certainly difficult too; I also don't know much Rust, and indeed there is a risk that we would lose users/contributors -- hence the suggestion to at least provide a compatible API.
