### ISSUE TITLE
Please add gousto.co.uk/cookbook/all-recipes

### ISSUE THREAD

**Issue by Jamzico** [hhursev/recipe-scrapers#140]
https://www.gousto.co.uk/cookbook/all-recipes

is there a way to go through all recipes on the site (i.e. only 20 recipes are shown at first... at the bottom of the page it says 'see more', how do you open this up to cycle through all recipes?)

example of a recipe url: 
https://www.gousto.co.uk/cookbook/pork-recipes/creamy-pork-tagliatelle

I am really new to coding and am really struggling to understand the html structure in the web scraping process! Thank you :)

**Comment by PatrickPierce** [comment]
I have started to work on a scraper for gousto and should have it finish before the weekend. This website is a little more complicated than others and it will a little bit of time.

I will explain the process of creating this scraper and how to loop through recipes on a site once I am finished.

**Comment by PatrickPierce** [comment]
I'll address the questions first, then explain how I scraped the data.

1. How to scrape multiple recipes on a website.
This isn't something that the module itself can do. You would need to loop through the div to add all recipe links to a list. Then access each item in list to run recipe_scrapers on it.

- Scrape the main div container that holds all the links to recipes
- Loop through container to grab the html href tags <a> into a list
- Loop through list to get URL
- Import recipe_scrapers to gather data

2. Expanding "see more" options.
You will need to use [Selerium](https://selenium-python.readthedocs.io/) to interact with Javascript. I would create a master list then any recipe you have scrape will get added to the master list and ignore to prevent rescraping once clicking on "see more".

Here is how I went about creating the scraper for Gousto.
- yields
This is inside a sub_div (panel-subheading) that is inside a main_div (ingredients). The main_div is reference by an ID while the sub_div is reference by class name. I always reference by ID if it is an option as there can only be one element by that ID. Class names can be shared between elements though. Find the div, by id 'ingredients', then inside that, find the div, by class 'panel-subheading' and return the text.

- ingredients
I created a container that reference the same main_div by id ingredients. (Note: I could create the container in yields since it is the same container, then pass it to ingredients to prevent repeating this part). The text for ingredients is in an object figcaption, by class 'indivrecipe-ingredients-text'. We will need to find_all elements since there are multiple objects that is referenced by object with class. Some recipes have an extra section with more ingredients. This is located in a nested div, by class 'panel-subheading' that is located inside another div, by class 'panel indivrecipe-panel'. I used strip() to remove the new line and new tab characters "\n\t" and then split(', ') to split the words into a list. Next we normalize_string on ingredients. After that we append each "extra" item in "extras" item to the ingredients list. This returns our full list of ingredients.

- ratings
This site uses images instead of text for their ratings. Lucky they provide a property for their images that we can use to look up. The div, by class 'star-overflow' has an image tag (img) that can we find by property 'alt'. I'm returning the name of the image file. The actual rating is the first character of the filename so I'm slicing only the first index to return the integer.


Hope that helps some. I only know basic HTML and CSS. You don't need to know a lot about HTML, CSS or JS to scrape the website, just how to navigate. Some modules to lookup is requests, beautifulsoup4 and selenium. These are the basic web scraping modules that will help get you started.

**Comment by Jamzico** [comment]
Thank you so much! I had a go at creating a scraper which cycles through a list of recipe URLs and pulls out the information I want. There are two parts I have struggled with:

1) Creating the master list of all URLs by using selenium to interface with the webpage - this is something I have no idea where to start with!

2) Error handling! how do I adapt the code to ignore recipes that don't have the right structure/information?

**Comment by Jamzico** [comment]
[gousto_recipe_scraper.txt](https://github.com/hhursev/recipe-scrapers/files/4638087/gousto_recipe_scraper.txt)
