### ISSUE TITLE
[Discussion] Relationship between this package and `scrape-schema-recipe`

### ISSUE THREAD

**Issue by bfcarpio** [hhursev/recipe-scrapers#196]
At some point there are just too many websites to make parsers for. It especially seems weird when many of them are just schema based websites.

[This other package](https://github.com/micahcochran/scrape-schema-recipe) seems to be a generic schema scraping package that doesn't need you to make parsers. 

It seems a bit fruitless for this package to continue to make parsers. Should we import the other package or become friends with the maintainer? Maybe we do a co-op and say something in the `README` about the package? Maybe we just focus more on non-schema websites and get our parsing to be very efficient?

Just wondered what thoughts were.

**Comment by jayaddison** [comment]
@bfcarpio Thanks for raising this conversation - I can offer a little bit of experience and opinion (some personal, some from friends and colleagues in companies who use web scraping).

Common schemas for web content are a great idea and get us 90% of the way towards an ecosystem where we can all gather and use web data for useful applications.

However in practice - for organizational, cultural, and legacy code reasons - individual websites always provide data with slightly different properties.  It may be guaranteed that, for example, [`recipeYield`](https://schema.org/recipeYield) is always going to be a text value - and since the web is ultimately text, that's fine.

But different websites will provide different sets of values in that field - `1 serving`, `"1"`, `1 item(s)`, etc.  This can also change over time, and sometimes websites may have bugs that mean that individual fields need special handling.

A generic schema parser is great in theory, but in practice there's frequently a need to perform per-website logic to extract and unify values.  Since we can't enforce that websites will all adhere to a specification about the _values_ of the schema (only the fields), there are always going to be situations like this.

In my opinion `recipe-scrapers` is precisely the place at which these data quality issues can be managed and handled -- and the more people who use the library, the more likely we are to catch those edge cases and handle them quickly.

It's not perfect yet, and may never be completely because this is messy, real-world data we're talking about -- the `recipeYields` example above was partly chosen because there's already ambiguity there.  But it'll improve over time and the ability to report and fix per-website bugs is, to me, a crucial feature rather than something that can be removed.

**Comment by bfcarpio** [comment]
Sorry, I don't mean to imply that we scrap everything here.

It seems as though that there's a really good combo to be gained out of using both of these packages together. [`recipe-parser`](https://github.com/boonepeter/recipe-parser) demonstrates what I was thinking where `scrape-schema-recipe` is for breadth while this package is for depth. For some projects, the inconsistencies of servings might not matter. [plainoldrecipe.com](plainoldrecipe.com) just takes the data and throws it on the page. `openculinary` will absolutely want more consistency and I hope to see the potential grocy integration take advantage of specific units. 

If I had a fledgling project it'd be nice if these projects returned data in a similar fashion or even had a recommended way to integrate them. I may be trying to build infrastructure where no one wants it :sweat_smile: . 

@jayaddison If all your needs are met with this single package that's great! I hope to continue working on it with you and others in the future.

**Comment by jayaddison** [comment]
@bfcarpio no probs - and yep, I think you're right that there's value in both libraries; one thing to note is that `recipe-scrapers` provides a base level of assurance that each scraper does work for the intended website, thanks to the process involved in adding each one.  It's a positive side-effect of the issue + pull request + test coverage.

There are ways to scale up that kind of quality testing in a way that should work across both schema-based and per-website scraper libraries, and if we steer in that kind of direction then it should become apparent how effective each approach is.

**Comment by hhursev** [comment]
Like the conversation here 😉 One of the reasons for adding _schemaorg.py is an option down to road to scrape websites not listed in the readme. Something as a "go wild" mode where if json-ld/microdata in "Recipe" like format is found on the site the package tries (safely) to parse it. This package, however, is intended to be opinionated and return expected format:

.title() -> string
.total_time() -> int
.yields() -> string 'X servings'
.ingredients() -> list of strings
.instructions() -> string
.ratings() -> float
.image() -> string

Now in here we face the imperfect world where even the [schema.org](https://schema.org/Recipe) rules are not a clear-cut. For example `recipeInstructions` can return 3 different formats by definition and on top of it some websites don't even respect that and return something in their own flavor.

"Go wild" would be a good addition imo and [extruct](https://github.com/scrapinghub/extruct) (that we already use) is our best friend for it. "Extructing" the data and trying to unify/normalize it to our expected output. I may be wrong, but I don't see much value in scrape-schema-recipe for our cause (I like the package, I have starred it myself ⭐ ) but it is a much simpler wrap around extruct compared to what I believe we should be implementing.

**Comment by micahcochran** [comment]
I am the creator of `scrape-schema-recipe`.  My intent was trying to create library that would give structured recipe output from most recipe websites. 

I think there is value in `recipe-scraper`.  I have contributed to this project, and stared ⭐ it too.

schema.org/Recipe (I'll use the term Recipe Schema hereon-out) has a pretty structured manner to represent recipes.  Even though there are few different forms of Recipe Schema (mostly Microdata and JSON-LD).

I've added some ways to parse some of the data, so that you can set a flag to get python objects instead of dates.

There are weaknesses to Recipe Schema.  I don't like the multiple ways to parse the recipeInstructions (HowToSteps versus strings).  The schema uses many different ways to represent the same things.  The parsing of ingredients is an artform in itself.  (Other recipe formats actually solved that issue.) I'm sure if I got back into the code, I could think of other instances.

There has not been interest in the contributing to the project `scrape-schema-recipe`.  The reboot of [`gourmet`](https://github.com/kirienko/gourmet) may be using `scrape-schema-recipe` as a plugin. (I hope they can get a release.)

One of the strengths of `scrape-schema-recipe` should be able to parse Recipe Schema data that is in any language.

If I were add features to `scrape-schema-recipe`, making output easier on the end programmer would be on the list.  I would welcome contributions to makes that library easier to use and adds to its richness.  If you have suggestions, where the output could be improved, please add an issue.

> If I had a fledgling project it'd be nice if these projects returned data in a similar fashion or even had a recommended way to integrate them. I may be trying to build infrastructure where no one wants it 😅 .

I've toyed with the idea.  I like that `scrape-schema-recipe` returns a dictionary that is similar to JSON-LD.  If you have a video URL of the recipe in there, it will just pass it along.   With `recipe-scrapers`, you might be able to get such an bird through the `.links()`, but would you know it is a video URL or some other URL?

My time programming these days is limited these days.  I'm doing very little to improve or update library.  I would like to think of myself as a friend to this project. I just like my project a little better.  :-)

**Comment by jayaddison** [comment]
Closing a few old issues - please comment, re-open or file a new issue for any unresolved items (preferably after checking for more recent discussion!).  Thank you.
