### ISSUE TITLE
[Meta] Travis CI builds no longer indicating on PRs

### ISSUE THREAD

**Issue by bfcarpio** [hhursev/recipe-scrapers#236]
@hhursev Did you make any changes recently to how Travis or the Repo is configured? For some reason, I'm no longer seeing new check-mark or red "x" icons by PRs and commits. However, if I manually go to Travis' website I can still find the results of its run.

I think having though indicators is helpful. Both for code quality and just so that others can see if code works.

**Comment by hhursev** [comment]
Hmmm, I haven't touched Travis/Repo configs for sure. Will look it up once I see a new PR open 😄

**Comment by bfcarpio** [comment]
![2020-10-16-230932_871x366_scrot](https://user-images.githubusercontent.com/48795231/96329753-b656fd80-1004-11eb-804a-6144df4d780d.png)

![2020-10-16-231022_873x360_scrot](https://user-images.githubusercontent.com/48795231/96329777-dbe40700-1004-11eb-8cdc-ae95b8a7c544.png)


Theres a difference between these pics! It's that little check mark by the commit and the big indicator about the travis checks. The weird thing is that Travis is still running:

https://travis-ci.org/github/hhursev/recipe-scrapers/builds/736030404

**Comment by hhursev** [comment]
In my PR it was due to the conflicts that needed to be resolved. Once resolved it show the badge same way as the other

**Comment by bfcarpio** [comment]
I used to see small red `x` or green check marks next to commits and have warnings when things did and didn't pass. I don't see things on your branch. Maybe it's only for those who submitted the PR?

**Comment by jayaddison** [comment]
Strange, I don't see the checkmarks on my latest PR either.

**Comment by wkarney** [comment]
I read [somewhere](https://travis-ci.community/t/travis-build-status-not-show-on-github/7990/4) that it might be that it is caused by travis-ci.org hitting the GitHub API rate limits. Switching to travis-ci.com was the suggested workaround. 

Furthermore, it seems like [travis-ci.org is being shutdown at the end of the year](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom).

Here is the [documentation](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) on the migration process to travis-ci.com. @hhursev @bfcarpio

**Comment by bfcarpio** [comment]
@wkarney Thank you for the updates!

We should make these changes sooner than later to ensure a consistent and happy repo, IMO.

**Comment by hhursev** [comment]
@wkarney thanks! migrating to travis-ci.com fixed this issue indeed :)
