### ISSUE TITLE
How to export data from scraper to spreadsheet?

### ISSUE THREAD

**Issue by smarotu** [hhursev/recipe-scrapers#244]
Hello, after running the recipe scraper in python I get the following code:
<recipe_scrapers.fitmencook.FitMenCook object at 0x000002A3399A21F0>

Is this correct? There are no instructions on what to do with this after you have run the package in python. I would like to export the information to a spreadsheet.

<img width="499" alt="Untitled" src="https://user-images.githubusercontent.com/73384044/97077930-65559380-161a-11eb-8efb-fd4c1ea21e37.png">

**Comment by bfcarpio** [comment]
You can assign the return of `scrape_me()` to a variable and then call accessor functions on it as shown in the `README`.

```python
scraper.title()
scraper.total_time()
scraper.yields()
scraper.ingredients()
scraper.instructions()
scraper.image()
scraper.host()
scraper.links()
```

Are you thinking of something like a CSV output? That might be a bit difficult since recipes would have nested data with list-structures. I don't believe CSV supports this.

If you really want this, you could write a function for the scraper class that outputs the data into a CSV format or your format of choice.

**Comment by jayaddison** [comment]
Closing a few old issues - please comment, re-open or file a new issue for any unresolved items (preferably after checking for more recent discussion!).  Thank you.
