### ISSUE TITLE
Download Data

### ISSUE THREAD

**Issue by mansigoel21** [hhursev/recipe-scrapers#430]
I used the scrapper and want to download the recipes as CSV, how can I do that?
Is there any way or I have to write the whole code again?

**Comment by bfcarpio** [comment]
Similar question to #244. A quick solution would be to make a dictionary from all the function calls and then just use a csv library to take those dictionaries and make them CSV files.

The better long term solution would be to make a PR that does something like the above or creates a `dataclass` on a function that's implemented on the base class. Then you could still use your CSV library to handle the dataclass since those are fairly standardized. 

The biggest issue with both of these solutions is nested data and when recipe pages have 2 recipes. That's just an issue with this scraper as a whole and we need to fix it.

**Comment by bfcarpio** [comment]
@mansigoel21 I think Micah's code is your best bet as I agree that CSV wouldn't be the best choice of format without some other massaging of the data.

@hhursev What's you opinion of including the export functionality into this package?

**Comment by jayaddison** [comment]
Closing a few old issues - please comment, re-open or file a new issue for any unresolved items (preferably after checking for more recent discussion!).  Thank you.
