### ISSUE TITLE
Is nutrients per serving, in total, or based off the websites own calculations?

### ISSUE THREAD

**Issue by ulfakerlind** [hhursev/recipe-scrapers#454]
Yepp, just like the title states :)
I'm guessing two pounds of turkey can impossibly only contain 230 calories, as one test-run showed. So it must be per serving

I couldn't find any clarification in your readme, so I thought id ask

Awesome stuff btw!

**Comment by cydanil** [comment]
It's the nutrients information as specified in the page, often defined per serving, as you've observed.  

It is possible for scrapers to customize the what the value is (eg. multiply it by number of servings as you've suggested), but 1) one would need to do it on a per-website basis, ensuring all their recipes have the same unit (serving or dish), and 2) I'm tempted to think that nutrients information is usually intended to be per serving/per person.

**Comment by bfcarpio** [comment]
@ulfakerlind I believe that @cydanil is correct. From what I've seen, the few scrapers that support nutrition will just grab it from the page instead of applying maths. I also personally agree with the sentiment that nutrients is per serving. 

Going to close this comment, but feel free to post further if required.
