### ISSUE TITLE
Gordon Ramsay scraper

### ISSUE THREAD

**Issue by Cassock** [hhursev/recipe-scrapers#461]
Good morning. Tried to import this recipe via Mealie and found that it's not supported:
https://www.gordonramsay.com/gr/recipes/beef-wellington/

**Comment by hay-kot** [comment]
Hey [Mealie](https://github.com/hay-kot/mealie) dev here. This can be closed, It's an issue with Mealie and how we're parsing the images on the server, NOT with the recipe-scrapers dependency. 

For future reference, you can use the debugger in the v1 beta site to identify if the the site is providing data. If it returns data then the problem is on our side, and not with recipe-scrapers.

Go to the homepage https://beta.mealie.io/ and Create > Debug and test the URL. 

I'm tracking this issue here 

- https://github.com/hay-kot/mealie/issues/881

**Comment by bfcarpio** [comment]
Thank you, @hay-kot , for informing us.

**Comment by hhursev** [comment]
just wanted to say very good job on mealie!!! @hay-kot thanks for informing us x2
