### ISSUE TITLE
[Discussion] Is there a point in officially adding a website where schema is supported?

### ISSUE THREAD

**Issue by drewtownchi** [hhursev/recipe-scrapers#469]
Many newer recipe sites work perfect fine with "wild_mode".  Is there a point in officially supporting these websites in the code base?  There are a few website I regularly use that aren't officially supported but seem to work just fine.

**Comment by jayaddison** [comment]
@drewtownchi I think the optimistic overall hope is that gradually speaking, recipe publishers move towards using more standardized and compatible metadata on their pages, and at that point libraries like this become less valuable compared to simple general retrieval-from-schema.

In reality I think we're a while from there yet, and so there's "default baseline retrieval" provided by the `wild_mode` option -- but if-and-when that doesn't work -- perhaps due to bugs or quirks on individual recipe websites -- then the ability to add a custom, more accurate scraper for that specific site can be valuable to people.

How often that happens is a bit up-in-the-air at the moment; off the top of my head, I haven't seen many scrapers that are mostly-schema-based-but-with-fixes.  As the community size grows, and as interest in the data quality grows, I'd expect we'll see more people care about individual fields on individual websites -- along with other issues, like choosing the best temporal version of a scraper to match the time a page was retrieved (but that's a whole other story).

**Comment by bfcarpio** [comment]
For my needs, I'll admit, if something works without an official scraper I won't bother. I also put the issues with a schema lower in my mental priority. Where this package shines is the more labourious raw HTML parsing scrapers.
