### ISSUE TITLE
recipe site suggestion

### ISSUE THREAD

**Issue by Wynne** [hhursev/recipe-scrapers#489]
https://www.maangchi.com/
https://omnivorescookbook.com/
https://www.justonecookbook.com/

**Comment by jayaddison** [comment]
These look great, thank you @Wynne!

To help our team add scrapers for these sites, I'll suggest one recipe from each of these:

- https://www.maangchi.com/recipe/yuringi (note: multiple images.  we will have to decide how to select the best image from the page -- maybe the last one because it shows the complete meal)
- https://omnivorescookbook.com/recipes/stir-fried-bok-choy-with-crispy-tofu (note: includes nutritional information on page)
- https://www.justonecookbook.com/miso-salmon/ (there is a lot of useful information on this page, although `recipe-scrapers` will only include the ingredient list, instructions, title, author, etc)

**Comment by jayaddison** [comment]
All three of these sites are added (and/or updated with fixes) in the the latest release, 14.20.0, now published to PyPi - thanks again, @wengtad for those contributions.
