### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by JagoMuhlehner** [hhursev/recipe-scrapers#533]
Hello, I'm kind of lost with the code is there by any chance a tutorial on how to scrape recipes using this scraper?

**Comment by jayaddison** [comment]
Hi @JagoMuhlehner - no problem - could you explain a bit more about what
you're trying to do?  (for example: scrape one recipe, scrape multiple
recipes from one website, scrape multiple recipes from multiple recipes...
or something else entirely)

**Comment by abarber229** [comment]
Hi @jayaddison. Sorry for hijacking this one, but instead of creating another tutorial question, how do I save the info? I didn't see anything in the wiki about where the output would save to. I tried using one of the hellofresh recipes for an example (https://www.hellofresh.com/recipes/peppercorn-steak-w06-5857fcd16121bb11c124f383) but nothing outputs to the console. I tried adding print(scraper) at the very end, but that returns `<recipe_scrapers.hellofresh.HelloFresh object at 0x0000021F78ECB010>`. Any thoughts on what I might be doing wrong? Thanks!

**Comment by bfcarpio** [comment]
@JagoMuhlehner You'll have to combine this library with another (like scrapy) to have it properly work. This library can get you the recipes when given a proper URL; however, scrapy will navigate around the site for you to properly find all the URLs. Finally, you'll have to use a database library and do some work to put all the recipes into a database. Unfortunately, I don't know much about using scrapy. `BeautifulSoup` will do something similar for you, but I believe you'll have to write more of the navigation logic yourself.

@abarber229 Output is saved inside that scraper object. To get the scraped data you must call one of the methods, `ingriedients()` for example.

**Comment by jayaddison** [comment]
I think this can be closed - we have some user guidance in the README, but as explained, we don't have a list of URLs to retrieve.  Please let us know if there's anything about the usage instructions that can be improved.
