### ISSUE TITLE
Custom settings error

### ISSUE THREAD

**Issue by goandgit** [hhursev/recipe-scrapers#536]
Hello,

I'm still a bit new to Python and have been playing with recipe-scrapers and I'm trying to add a custom settings file to the project but I'm having an issue. This is for version 13.32 running on Python 3.8, and Flask. My folder structure is as follows:
```
custom
 |-settings
    scraper.py
    __init__.py (blank)
venv
test_scraper.py (main entry point)
```

In test_scraper.py I have:
```
from recipe_scrapers import scrape_me
from recipe_scrapers.settings import settings
```

I've set
`RECIPE_SCRAPERS_SETTINGS=custom.settings.scraper.py`

On the first call to the API I get the following error:

`ModuleNotFoundError: No module named 'custom.settings.scraper.py'; 'custom.settings.scraper' is not a package`

On the next call it works.

From what I can tell it is breaking at this line:
```
# venv/lib/python3.8/site-packages/recipe_scrapers/settings/__init__.py
user_settings = importlib.import_module(user_settings)
```

I've been trying to fix it so I could submit a PR but I'm not having any success.

**Comment by hhursev** [comment]
You can try two things:

1) in bash `export RECIPE_SCRAPERS_SETTINGS=custom.settings.scraper` before you start your python app - similar to how you set env [variables for Flask - FLASK_APP or FLASK_ENV](https://flask.palletsprojects.com/en/2.1.x/quickstart/#a-minimal-application)

2) Another thing to try is in the .py file instead of `RECIPE_SCRAPERS_SETTINGS=...` do:

```
import os
os.environ["RECIPE_SCRAPERS_SETTINGS"] = "custom.settings.scraper"
```

The original implementation intend was to set env variable with `export ...` from bash. Sorry for not documenting properly (matter of fact I just recently removed the instructions from the README.md). I was under the impression that no one is using the custom settings functionality.

**Comment by goandgit** [comment]
I had that value in my .bashrc file instead of the export but I see my problem was the .py extension. Removing it fixed the problem. I read your comments in your source code which explained it but I didn't know to leave out the extension. Just my inexperience with Python I guess. Thank you.
