### ISSUE TITLE
total_time(), cook_time() and prep_time() return error or 0 for recipes from thekitchn.com

### ISSUE THREAD

**Issue by EnergyResearcher** [hhursev/recipe-scrapers#606]
Attempted code:
```
from recipe_scrapers import scrape_me
scraper = scrape_me('https://www.thekitchn.com/vegetarian-chili-266017')

scraper.total_time()     # returns 0
scraper.cook_time()     # returns NotImplementedError (same for prep_time())
scraper.schema.total_time()     # returns 0
scraper.schema.cook_time()     # returns 0 (same for prep_time())
```

With a different recipe `scraper.schema.cook_time()` and `scraper.schema.prep_time()` return `SchemaOrgException: recipe-scrapers exception: Preptime information not found in SchemaOrg`.

Python version 3.10.6 running on Windows 10.

**Comment by jayaddison** [comment]
Thanks @EnergyResearcher - in this case it looks like the cause is that the recipe's total time is specified in an [ISO 8601 duration format](https://en.wikipedia.org/wiki/ISO_8601#Durations) (`PT4200S` - 4,200 seconds) that isn't currently recognized by this library.

I'm developing a small fix that should resolve this.

**Comment by EnergyResearcher** [comment]
Thanks @jayaddison, I added your changes to the library (too impatient to wait for the merge of PR haha) and it worked! (Total time works with the scraper itself but for the prep time and cook time I still need to use scraper.schema which is fine with me)
