### ISSUE TITLE
Site: https://www.argiro.gr/

### ISSUE THREAD

**Issue by ioannamariapapakonstantinou** [hhursev/recipe-scrapers#693]
Some links:

-  https://www.argiro.gr/recipe/kraker/
- https://www.argiro.gr/recipe/gemista-tis-argiros/
- https://www.argiro.gr/recipe/kotopoulo-me-patates-sto-fourno/

**Comment by jayaddison** [comment]
Some good news and some not-so-great news related to this feature request:

  * Support for this website was added in #958.
  * Unfortunately testing current versions of the website for the provided URLs, a bug has appeared: #1363

I'm going to close this issue since we have added support for the site, but we'll want to fix that bug soon.
