### ISSUE TITLE
Updating existing scrapers to support ingredient groups

### ISSUE THREAD

**Issue by strangetom** [hhursev/recipe-scrapers#799]
The infrastructure to support returning ingredient groups from scrapers is now available in the latest release  (#781). For this to be useful, existing scrapers need to be updated to implement the `.ingredient_groups()` function for sites that group ingredients in their recipes. 

I've opened this issue so there is a place to keep track of which sites support returning ingredient groups and  to suggest scrapers that could be updated. **This is only to suggest updates to existing scrapers, not to suggest new scrapers.**

There are 5 sites supported at the moment, and I have identified a few more that can be supported with an update. 

## Supports `ingredient_groups()`

- AddAPinch
- AllTomat
- AltonBrown
- AmazingRibs
- ArchanasKitchen
- BakingMischief
- BakingSense
- BareFootContessa
- BBCGoodFood
- BettyCrocker
- BiancaZapatka
- BigOven
- BlueJeanChef
- BudgetBytes
- Delish
- DomesticateMe
- FoodFidelity
- HalfBakedHarvest
- LifestyleOfAFoodie
- LivelyTable
- NHSHealthierFamilies
- NIHHealthyEating
- NoRecipes
- Number2Pencil
- NYTimes
- OnceUponAChef
- PickUpLimes
- PinkOwlKitchen
- PlatingPixels
- PlowingThroughLife
- RainbowPlantLife
- RealFoodTesco
- RedHouseSpice
- SaboresAnjinomoto
- SteamyKitchen
- TasteAU
- TheCleverCarrot
- TheMagicalSlowCooker
- ThePioneerWoman
- TheSpruceEats
- TidyMom
- Tofoo
- TwoPeasAndTheirPod
- VanillaAndBean
- WeAreNotMartha

## Could support `ingredient_groups()` with an update

- AmbitiousKitchen (This one is going to be awkward. The group headings are return from .ingredients(), so the test that checks the consistency of ingredients between .ingredients() and .ingredient_groups() will fail because the group headings are not present in list of ingredients for each group.)
- KptnCook (@gloriousDan )
- jamieoliver.com 
- seriouseats.com 
- tasteofhome.com
- tastykitchen.com
- simplyrecipes.com

## Suggest a scraper that could support `ingredient_groups()`?
If you know of a currently supported site that needs updating to support ingredient groups, feel free to add it to this issue. It would be helpful if you can also provide two examples recipes: one that has ingredient groups, one that doesn't have ingredient groups. We need the scrapers to support both cases, so we need to test both cases.

If you want to make the updates yourself, then here's what you need to know.
1. `.ingredient_groups()` needs to be implemented in the scraper class
2.  `.ingredient_groups()` returns a list of `IngredientGroup` dataclasses. The dataclass is defined in the `_grouping_utils.py` file, so the scraper will need to import it from there.
3. Many sites follow a similar structure in the html markup for ingredients and group headings. There is a helper function in `_grouping_utils.py` called `group_ingredients` which takes the list of ingredients, the html markup soup object and the CSS selectors for the group headings and ingredients as arguments, and returns a list of `IngredientGroup` objects. I think this will all that is needed in many cases. You can look at the [BBCGoodFood](https://github.com/hhursev/recipe-scrapers/blob/main/recipe_scrapers/bbcgoodfood.py) or [RainbowPlantLife](https://github.com/hhursev/recipe-scrapers/blob/main/recipe_scrapers/rainbowplantlife.py) scrapers for examples of using this.
4. If the helper functions aren't appropriate, then the scraper will need to implement the `ingredient_groups()` function itself. [NIHHealthyEating](https://github.com/hhursev/recipe-scrapers/blob/main/recipe_scrapers/nihhealthyeating.py) is an example of a scraper that does this.
5. There need to be two test files for the updated scrapers:
    -   A test file for a recipe that doesn't group the ingredients
    -   A test file for a recipe that does group the ingredient
6. The tests should check all the usual things, including that the groups and the ingredients in each group are correct for the recipe. There is already an inherited test for every scraper which checks that the same ingredients are return from `.ingredients()` and `.ingredient_groups()` so there is no need to write that test.

Edit: 20240906: reflect that ArchanasKitchen and LivelyTable have ingredient grouping support.

**Comment by jayaddison** [comment]
Hi @strangetom - two comments/thoughts:

- Could you assign me one of the potentially-to-be-added scrapers?  I'd like to get some experience with how this feature works from a developer perspective.
- Would additional data from RecipeRadar be helpful?  I had in mind that I could run a query for recipes/sites with English-language ingredient lines that start with the text "For the ...".  From experience, that's a common sign that a recipe contains groupings.

**Comment by strangetom** [comment]
Hi @jayaddison 

RealFoodTesco is probably a good one to start with. I think you should be able to use the `group_ingredients` helper.

I didn't have much of a plan for identifying scrapers we could update, hence opening this issue to try a crowd source it. If there's anything we could do to automatically identify recipes, that would be great!

**Comment by gloriousDan** [comment]
@strangetom The KptnCook scraper should support ingredient groups. I'll try to implement it when I find some time hopefully soon.

**Comment by jayaddison** [comment]
Thanks @strangetom - I'm commencing work on ingredient group support for RealFoodTesco today.

**Comment by jayaddison** [comment]
@strangetom this error message was confusing when one of the CSS filters I applied returned no elements - could there be a way to provide the developer with a more detailed error message?

```
  File "<...home...>/recipe-scrapers/recipe_scrapers/_grouping_utils.py", line 76, in best_match
    index, _ = max(enumerate(scores), key=lambda x: x[1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence
```

**Comment by jayaddison** [comment]
I've now also been confused by what turned out to be a failure of `test_consistent_ingredients_lists` -- that test can begin failing when the `ingredient_groups` method is work-in-progress / incomplete, and that's a change from previous scraper development where, for the most part, implementing any individual recipe field extraction method would be completely independent of the tests for any other field.

**Comment by jayaddison** [comment]
> I didn't have much of a plan for identifying scrapers we could update, hence opening this issue to try a crowd source it. If there's anything we could do to automatically identify recipes, that would be great!

Included below are a few URLs that look to me like they'll exhibit grouping of ingredients, based on simple text pattern matching.

For transparency: the dataset these URLs are from is _basically_ the latest version of the now-unfortunately-discontinued [`openrecipes`](https://github.com/fictivekin/openrecipes) dataset -- with each URL resolved by following any HTTP redirects from the RecipeRadar crawler client.  There are potentially a small number of additional URLs that have been added by some currently-inactive functionality in RecipeRadar that is designed to search on-demand for additional, potentially unknown-to-the-service recipes on the web by relaying the queries that our users make.

Some of the URLs could be slightly outdated because refreshing of the crawled recipes occurs infrequently at the moment.

I've filtered the SQL query to retrieve results so that only domains where recipe crawling is enabled are included, for no particular reason other than it feels slightly more cautious.

If you'd like to replicate similar results in future: the database for RecipeRadar's backend should be published at some point -- I've mentioned that before to the OpenFoodFacts folks during a separate task I was working on, but have not yet actually gotten around to setting up the infrastructure to take regular RecipeRadar database backups and publish them.

Anyway; the query to retrieve these results is:

```sql
WITH domain_recipes (domain, url, sample, rn) AS
(
    SELECT r.domain, r.dst, ri.description, ROW_NUMBER() OVER (PARTITION BY r.domain ORDER BY NULL)
    FROM recipe_ingredients AS ri
    JOIN recipes AS r ON r.id = ri.recipe_id
    JOIN domains AS d ON d.domain = r.domain
    WHERE (ri.description ILIKE 'for the%' OR ri.description ILIKE '%:')
    AND NOT d.crawl_enabled IS false
)
SELECT domain, url, sample
FROM domain_recipes
WHERE rn = 1
ORDER BY domain ASC
```

And, finally, the part that's more directly relevant to this thread:

| domain | url | sample |
| ------ | --- | ------ |
| 101cookbooks.com | https://www.101cookbooks.com/archives/detoxifying-mint-tea-recipe.html | Dry mixture: |
| ambitiouskitchen.com | https://www.ambitiouskitchen.com/sweet-potato-salmon-cakes/ | Optional slaw for serving with the cakes: |
| jamieoliver.com | https://www.jamieoliver.com/recipes/beef-recipes/best-chargrilled-steak/ | For the salsa verde |
| seriouseats.com | https://www.seriouseats.com/oyakodon-japanese-chicken-and-egg-rice-bowl-recipe | To Serve: |
| steamykitchen.com | https://steamykitchen.com/38468-ruths-chris-sweet-potato-casserole-recipe.html | Crust Topping Mixture: |
| tasteofhome.com | https://www.tasteofhome.com/recipes/creamy-black-bean-dip/ | TOPPING: |
| tastykitchen.com | https://tastykitchen.com/recipes/soups/cheeseburger-soup-10/ | OPTIONAL GARNISH: |
| thepioneerwoman.com | https://thepioneerwoman.com/cooking/springy-flower-pot-desserts-a-blast-from-my-past/ | Other Things You'll Need: |

**Comment by strangetom** [comment]
@jayaddison Thanks for the feedback, it looks there are some changes we could make to improve the experience.

Two things come to mind based on your comments:

1. Related to the error you mention above, we could probably do with some checks in `group_ingredients()` function before we try to group the ingredients. For example, we could raise an exception if the CSS selector doesn't find the same number of ingredients as `.ingredients()` has. Something like
```python
def group_ingredients(...):
    ...
    found_ingredients = soup.select(group_element)
    if len(found_ingredients) != len(ingredients_list):
        raise ValueError(f"Found {len(found_ingredients} but was expecting to find {len(ingredients_list)}.")

    ... # the rest of the function
```

2. More generally, I think it would be a good idea to write a more detailed how to guide for developing scrapers. It would be good to document the steps involved and some expectations for things like tests.

Your point about the `test_consistent_ingredients_lists` is a good one and I don't have any suggestions at the moment.

**Comment by strangetom** [comment]
It occurs to me that we can use @jayaddison's approach on the archive of recipe html files we have in `tests/test_data`.

Using the following snippet
```python
results = {}
for testhtml in glob.glob("tests/test_data/*.testhtml"):
    with open(testhtml, "r") as f:
        soup = BeautifulSoup(f.read())

    body = soup.find("body")
    if not body:
        continue

    matches = body.findAll(string=re.compile("^For the", flags=re.I))
    if matches != []:
        results[testhtml] = matches
```

and a quick check of the results gives as a few more scrapers that can be updated

| domain | url | sample |
|--------|--------|--------|
| livelytable.com | https://livelytable.com/easy-chipotle-shrimp-tacos | For the cilantro jalapeño sauce: |
| simplyrecipes.com | https://www.simplyrecipes.com/parsnip-lobster-rolls-recipe-6944750 | For the roasted parsnips: |
| archanaskitchen.com | https://www.archanaskitchen.com/classic-greek-salad-recipe | For the dressing |
| thespruceeats.com | https://www.thespruceeats.com/doner-kebab-recipe-4171703 | For the Kebab: |
| vanillaandbean.com | https://vanillaandbean.com/maple-oat-sourdough-sandwich-bread | For the Soaker:  |
| redhousespice.com | https://redhousespice.com/char-siu-chinese-bbq-pork | For the marinade |
| steamykitchen.com | https://steamykitchen.com/56719-instant-pot-vietnamese-chicken-pho.html | For the Pho |
| delish.com | https://www.delish.com/cooking/recipe-ideas/recipes/a56732/pumpkin-cheesecake-roll-recipe/ | For the cake |
| twopeasandtheirpod.com | https://www.twopeasandtheirpod.com/baked-chicken-taquitos/ | For the Taquitos: |
| theclevercarrot.com | https://www.theclevercarrot.com/2017/12/how-to-make-sourdough-cinnamon-rolls-step-by-step-guide/ | For the Glaze |
| domesticate-me.com | https://domesticate-me.com/dude-diet-buffalo-chicken-quinoa-bake/ | For the Yogurt Ranch: |

**Comment by jknndy** [comment]
Grouped ingredients support added to Domesticate-me (#823), theclevercarrot (#824) & Delish (#825)

I am having issues getting the test_consistent_ingredients_list to not return an error on the non-grouping test for thespruceeats #826, if anyone could take a look and weigh in that'd be great.

**Comment by jayaddison** [comment]
> If you'd like to replicate similar results in future: the database for RecipeRadar's backend should be published at some point -- I've mentioned that before to the OpenFoodFacts folks during a separate task I was working on, but have not yet actually gotten around to setting up the infrastructure to take regular RecipeRadar database backups and publish them.

These RecipeRadar PostgreSQL datbase backups are now available under the terms of the [Open Database License (ODbL)](https://opendatacommons.org/licenses/odbl/), for anyone who'd like to run similar queries using that data in future: https://backups.reciperadar.com/

**Comment by jayaddison** [comment]
> These RecipeRadar PostgreSQL datbase backups are now available under the terms of the [Open Database License (ODbL)](https://opendatacommons.org/licenses/odbl/), for anyone who'd like to run similar queries using that data in future: https://backups.reciperadar.com/

Admitting two mistakes here:

Last week I realized that since 2023-08-28 (https://github.com/openculinary/backups/commit/5ed5393b75dd7c9af2297223105603d1e1cb1e04) these backups had contained `instructions` (recipe directions) text.  I removed those on 2023-10-16 (https://github.com/openculinary/backend/commit/a5a314e2ea15bffffaa7706bb52c7d2b4fd671b4) and wouldn't have published the backups and mentioned them here knowing that those were in the content.

Another oversight is that the `domains` table contained some publicly-sourced email addresses for recipe sites, and also the status of RecipeRadar's contact with them.  I've unpublished that data as of today (https://github.com/openculinary/backups/commit/352c372fdfcf78f2f87eb56796dc5f46a508bea7).

If you've downloaded copies of the affected backup databases, and/or loaded them into database systems, or know folks who have: I'd kindly ask if you could delete those or pass along the request for them to be deleted.

(seemingly off-topic, I know - I want this database to be able to help guide the quality of scrapers here, but that also needs to be done carefully so as not to cause problems -- and I think it's better to be open about mistakes made along the way)

**Comment by jayaddison** [comment]
We have fairly extensive support for ingredient groups across the codebase now, so I think we can probably close this, unless anyone would prefer to keep it open?

**Comment by jknndy** [comment]
Agreed! There are still plenty of sites to add coverage for but I think we've got substantial coverage as of now
